CREATE TABLE TB_USUARIO(
    SQ_USUARIO bigserial primary key,
    DS_NOME_USUARIO varchar(50),
    DS_EMAIL varchar(50),
    DS_SENHA varchar(20),
    DS_CAMINHO_IMAGEM varchar(300)
);

CREATE TABLE TB_CAMPANHA(
	SQ_CAMPANHA bigserial primary key,
	DS_TITULO_CAMPANHA varchar(60),
	DS_IMAGEM_CAMPANHA varchar(300),
	DS_CAMPANHA varchar(300),
	SQ_USUARIO bigint,
	CONSTRAINT FK_CAMPANHA_USUARIO FOREIGN KEY(SQ_USUARIO) REFERENCES TB_USUARIO(SQ_USUARIO)
);

CREATE TABLE TB_TIPO_PERSONAGEM(
	SQ_TIPO_PERSONAGEM bigserial primary key,
	DS_TIPO_PERSONAGEM varchar(20)
);

CREATE TABLE TB_TIPO_HABILIDADE(
	SQ_TIPO_HABILIDADE bigserial primary key,
	DS_TIPO_HABILIDADE varchar(20)
);

CREATE TABLE TB_TIPO_EVENTO_CAMPANHA(
	SQ_TIPO_EVENTO_CAMPANHA bigserial primary key,
	DS_TIPO_EVENTO_CAMPANHA varchar(20)
);

CREATE TABLE TB_STATUS_COMBATE(
	SQ_STATUS_COMBATE bigserial primary key,
	DS_STATUS_COMBATE varchar(20)
);


CREATE TABLE TB_PERSONAGEM(
	SQ_PERSONAGEM bigserial primary key,
	DS_NOME_PERSONAGEM varchar(50),
	DS_RACA varchar(20),
	DS_CLASSE varchar(20),
	SQ_CAMPANHA bigint,
	NR_PONTOS_VIDA integer,
	DS_IMAGEM varchar(300),
	TP_PERSONAGEM bigint,
	NR_NIVEL_PERSONAGEM integer,
	CONSTRAINT FK_PERSONAGEM_TIPO_PERSONAGEM FOREIGN KEY(TP_PERSONAGEM) REFERENCES TB_TIPO_PERSONAGEM(SQ_TIPO_PERSONAGEM),
	CONSTRAINT FK_PERSONAGEM_CAMPANHA FOREIGN KEY(SQ_CAMPANHA) REFERENCES TB_CAMPANHA(SQ_CAMPANHA)
);

CREATE TABLE TB_HABILIDADE(
	SQ_HABILIDADE bigserial primary key,
	DS_NOME_HABILIDADE varchar(20),
	SQ_PERSONAGEM bigint,
	TP_HABILIDADE bigint,
	DS_HABILIDADE varchar(100),
	CONSTRAINT FK_HABILIDADE_PERSONAGEM FOREIGN KEY(SQ_PERSONAGEM) REFERENCES TB_PERSONAGEM(SQ_PERSONAGEM),
	CONSTRAINT FK_HABILIDADE_TIPO_HABILIDADE FOREIGN KEY(TP_HABILIDADE) REFERENCES TB_TIPO_HABILIDADE(SQ_TIPO_HABILIDADE)
);

CREATE TABLE TB_COMBATE(
	SQ_COMBATE bigserial primary key,
	DT_COMBATE date,
	DS_RESUMO_COMBATE text,
	SQ_CAMPANHA bigint,
	ST_COMBATE 	bigint,
	DS_TITULO_COMBATE varchar(50)
	CONSTRAINT FK_COMBATE_CAMPANHA FOREIGN KEY(SQ_CAMPANHA) REFERENCES TB_CAMPANHA(SQ_CAMPANHA),
	CONSTRAINT FK_COMBATE_STATUS_COMBATE FOREIGN KEY(ST_COMBATE) REFERENCES TB_STATUS_COMBATE(SQ_STATUS_COMBATE)
);

CREATE TABLE TB_PERSONAGEM_COMBATE(
	SQ_PERSONAGEM_COMBATE bigserial primary key,
	SQ_PERSONAGEM bigint,
	SQ_COMBATE bigint,
	NR_ORDEM_COMBATE bigint
	CONSTRAINT FK_PERSONAGEMCBT_PERSONAGEM FOREIGN KEY(SQ_PERSONAGEM) REFERENCES TB_PERSONAGEM(SQ_PERSONAGEM),
	CONSTRAINT FK_PERSONAGEMCBT_COMBATE FOREIGN KEY(SQ_COMBATE) REFERENCES TB_COMBATE(SQ_COMBATE)
);

CREATE TABLE TB_ANOTACAO(
	SQ_ANOTACAO bigserial primary key,
	SQ_CAMPANHA bigint,
	DS_ANOTACAO varchar(300),
	CONSTRAINT FK_ANOTACAO_CAMPANHA FOREIGN KEY(SQ_CAMPANHA) REFERENCES TB_CAMPANHA(SQ_CAMPANHA)
);

CREATE TABLE TB_EVENTO_CAMPANHA(
	SQ_EVENTO_CAMPANHA bigserial primary key,
	TP_EVENTO_CAMPANHA bigint,
	SQ_CAMPANHA bigint,
	DT_EVENTO date,
	SQ_PERSONAGEM bigint,
	SQ_COMBATE bigint,
	SQ_ANOTACAO bigint,
	CONSTRAINT FK_EVENTO_CAMPANHA_TIPO_EVENTO FOREIGN KEY(TP_EVENTO_CAMPANHA) REFERENCES TB_TIPO_EVENTO_CAMPANHA(SQ_TIPO_EVENTO_CAMPANHA),
	CONSTRAINT FK_EVENTO_CAMPANHA_CAMPANHA FOREIGN KEY(SQ_CAMPANHA) REFERENCES TB_CAMPANHA(SQ_CAMPANHA),
	CONSTRAINT FK_EVENTO_CAMPANHA_PERSONAGEM FOREIGN KEY(SQ_PERSONAGEM) REFERENCES TB_PERSONAGEM(SQ_PERSONAGEM),
	CONSTRAINT FK_EVENTO_CAMPANHA_COMBATE FOREIGN KEY(SQ_COMBATE) REFERENCES TB_COMBATE(SQ_COMBATE),
	CONSTRAINT FK_EVENTO_CAMPANHA_ANOTACAO FOREIGN KEY(SQ_ANOTACAO) REFERENCES TB_ANOTACAO(SQ_ANOTACAO)
);